### ISSUE TITLE
[Wrong instruction?] Lesson 19

### ISSUE THREAD

**Issue by kiki-m** [makersacademy/escape-precourse-issues#7]
~~>grep binary *.txt~~ 
~~produces nothing~~

~~should be replaced with~~
~~>grep binary *Text~~
~~and the screenshot updated~~

**Comment by nikeshashar** [comment]
If you break apart the instructions - what's `grep` specifically doing here?

**Comment by nikeshashar** [comment]
Might one to pair on with someone in the group?

**Comment by kiki-m** [comment]
Please ignore - clearly understood.

To answer your question: grep searches for the word binary in both lower and upper case characters in all txt files in the current dir.

**Comment by kiki-m** [comment]
Please ignore - clearly understood.

To answer your question: grep searches for the word binary in both lower and upper case characters in all txt files in the current dir.
